import {Metadata} from "next";
import Navbar from "@/app/Components/Navbar";
import Footer from "@/app/Components/Footer";

export const metadata: Metadata = {
    title: "About us | Service & Education",
    // description: "Generated by create next app",
};

const Page = () => {

    return(
        <>
            <Navbar/>
            <div className="p-5">
                <p className="font-bold text-xl">About us</p>
                Welcome to Service and Education, your premier destination for high-quality target boards and educational resources.

                At Service and Education, we are driven by a passion for excellence and a commitment to customer satisfaction. Our journey began with a simple idea: to provide enthusiasts and learners with access to top-notch products and valuable educational materials that inspire growth and development.

                Our mission is clear: to empower individuals to excel in their pursuits, whether it is mastering the art of target shooting or expanding their knowledge through our curated educational resources. We believe in the power of education to transform lives and the importance of quality tools to support skill development.

                What sets us apart is our dedication to sourcing only the best products and resources, ensuring that every item you purchase from us meets the highest standards of quality and reliability. Whether you are a seasoned professional or a beginner just starting out, you can trust Service and Education to provide you with the tools and guidance you need to succeed.

                Join us on this journey of discovery and growth. Experience the difference with Service and Education.

                <br/>
                <br/>

                <b> You can visit our office: <br/>
                Aadarsh colony , Road no 4 khemnichak, Patna, Bihar, 800027
            </b>
            </div>
            <Footer/>
        </>
    )
}
export default Page;
