import { Metadata } from "next";
import Navbar from "@/app/Components/Navbar";
import Footer from "@/app/Components/Footer";

export const metadata: Metadata = {
  title: "About us | Service & Education",
  // description: "Generated by create next app",
};

const Page = () => {
  return (
    <>
      <Navbar />
      <div className="p-5 space-y-4">
        <p className="font-bold text-xl">About Us</p>

        <p>
          Welcome to <strong>Service and Education</strong>, your trusted destination for high-quality educational books and resources.
        </p>

        <p>
          Operated by <strong>Kundan Kumar</strong>, our platform is dedicated to supporting students, educators, and learners by providing carefully selected books that align with academic standards and competitive exam requirements.
        </p>

        <p>
          Our mission is to empower individuals through accessible and affordable education. Whether you're preparing for exams or deepening your knowledge, our curated selection of books is here to support your journey.
        </p>

        <p>
          What sets us apart is our commitment to quality, authenticity, and customer satisfaction. Every book we offer is sourced with care to ensure accuracy, relevance, and educational value.
        </p>

        <p>
          From school textbooks to exam preparation materials, <strong>Service and Education by Kundan Kumar</strong> is here to guide your learning journey.
        </p>

        <p>
          Thank you for choosing us. Join our growing community of learners and experience the difference.
        </p>

        <div className="pt-4">
          <p className="font-semibold">
            📍 You can visit our office:
          </p>
          <p>
            Aadarsh Colony, Road No. 4, Khemnichak,<br />
            Patna, Bihar – 800027
          </p>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default Page;
