import {Metadata} from "next";
import Navbar from "@/app/Components/Navbar";
import Footer from "@/app/Components/Footer";

export const metadata: Metadata = {
    title: "Contact us| Service & Education",
    // description: "Generated by create next app",
};

const Page = () => {

    return(
        <>
            <Navbar/>
                <div className="p-5">
                    <p className="font-bold text-xl">Contact us</p>
                    Have a question or need assistance? Our friendly and knowledgeable team is here to help!

                    You can reach Service and Education through the following channels:
                    <br/>
                    <strong>Phone: +919798190774 </strong>
                    <br/>
                    <strong>Email: contact@targetboardstore.com</strong>
                    <br/>
                    <b> You can visit our office: <br/>
                        Aadarsh colony , Road no 4 khemnichak, Patna, Bihar, 800027
                    </b>
                    <br/>
                    We value your feedback and strive to provide prompt and helpful support to all our customers. Do not hesitate to get in touch with us – we are here to assist you every step of the way.
                </div>
            <Footer/>
        </>
    )
}
export default Page;
