import {Metadata} from "next";
import Navbar from "@/app/Components/Navbar";
import Footer from "@/app/Components/Footer";

export const metadata: Metadata = {
    title: "Privacy Policy | Service & Education",
    // description: "Generated by create next app",
};

const Page = () => {

    return(
        <>
            <Navbar/>
            <div className="p-5">
                <p className="font-bold text-xl">Privacy policy</p>
                Protecting your privacy and safeguarding your personal information is a top priority for us at Service and Education. Our Privacy Policy outlines the following:

                Information We Collect: We may collect personal information such as your name, email address, shipping address, and payment information when you place an order or register an account on our website.
                How We Use Your Information: We use your personal information to process your orders, communicate with you, and improve our products and services.
                Security Measures: We employ industry-standard security measures to protect your personal information from unauthorized access, disclosure, or alteration.
                Your Rights: You have the right to access, correct, or delete your personal information. You may also choose to opt-out of receiving marketing communications from us.
                For a detailed overview of our privacy practices, please review our Privacy Policy page.
            </div>
            <Footer/>
        </>
    )
}
export default Page;
