import {Metadata} from "next";
import Navbar from "@/app/Components/Navbar";
import Footer from "@/app/Components/Footer";

export const metadata: Metadata = {
    title: "Terms & Conditions | Service & Education",
    // description: "Generated by create next app",
};

const Page = () => {

    return(
        <>
            <Navbar/>
            <div className="p-5">
                <p className="font-bold text-xl">Terms & Conditions</p>
                Our Terms and Conditions govern the use of our website and the purchase of products from Service and Education.
                <br/>
                Here is an overview of some key points covered in our terms:

                Terms of Service: By using our website and purchasing products from us, you agree to abide by our terms of service.
                Order Acceptance: All orders placed through our website are subject to acceptance and availability.
                Payment Terms: Payment for orders must be made in full at the time of purchase.
                Product Availability: Product availability is subject to change without notice. We reserve the right to limit the quantity of products available for purchase.
                Limitation of Liability: Service and Education shall not be liable for any indirect, incidental, special, or consequential damages arising out of the use or inability to use our products or website.
                For the complete terms and conditions, please refer to our Terms and Conditions page.
            </div>
            <Footer/>
        </>
    )
}
export default Page;
