import {Metadata} from "next";
import Navbar from "@/app/Components/Navbar";
import Footer from "@/app/Components/Footer";

export const metadata: Metadata = {
    title: "Shipping | Service & Education",
    // description: "Generated by create next app",
};

const Page = () => {

    return(
        <>
            <Navbar/>
            <div className="p-5">
                <p className="font-bold text-xl">Shipping Policy</p>
                <p>At Service and Education, we prioritize timely and reliable shipping to meet your needs.</p>
                <p>Here are key details about our shipping policy:</p>
                <ul>
                    <li><strong>Shipping Destinations:</strong> We ship to addresses within India only.</li>
                    <li><strong>Processing Time:</strong> Orders are processed and shipped within 1 day after payment verification. Deliveries within Bihar typically take 4 to 6 days after ordering. Deliveries to locations outside Bihar may require additional transit time depending on the distance.</li>
                    <li><strong>Shipping Costs:</strong> Costs vary based on destination and package weight. Exact shipping costs are provided at checkout.</li>
                    <li><strong>Tracking Information:</strong> You will receive a tracking number by email once your order is shipped. This number can be used to check the status of your delivery.</li>
                    <li><strong>Delivery Time:</strong> Delivery times vary based on shipping method and location. Refer to the estimated delivery times provided during checkout.</li>
                </ul>
                <p>For more details or if you have any questions, please <strong>contact us</strong>.</p>
                <p><strong>Shipping Address:</strong> Aadarsh Colony, Road no 4 Khemnichak, Patna, 800027</p>
            </div>
            <Footer/>
        </>
    )
}
export default Page;
