import {Metadata} from "next";
import Navbar from "@/app/Components/Navbar";
import Footer from "@/app/Components/Footer";

export const metadata: Metadata = {
    title: "Cancellation/Refund Policy | Service & Education",
    // description: "Generated by create next app",
};

const Page = () => {

    return(
        <>
            <Navbar/>
            <div className="p-5">
                <p className="font-bold text-xl">Cancellation/Refund Policy</p>
                <p>We understand that situations may arise where you need to cancel an order or request a refund. Below are the details of our cancellation and refund policy:</p>
                <ul>
                    <li><strong>Order Cancellation:</strong> If you wish to cancel your order, please contact us as soon as possible. We will make every effort to accommodate your request. However, please be aware that orders that have already been processed may be subject to a cancellation fee.</li>
                    <li><strong>Refund Eligibility:</strong> Refunds are available for eligible products returned within 24 hours of purchase. Products must be unused and in their original condition to qualify for a refund.</li>
                    <li><strong>Refund Processing:</strong> Refunds will be processed within 3 business days after we receive the returned product. Please note that original shipping charges are non-refundable.</li>
                    <li><strong>Return Shipping:</strong> Customers are responsible for the cost of return shipping unless the product is defective or was damaged upon arrival.</li>
                </ul>
                <p>For more detailed information on our cancellation and refund procedures, please visit our <strong>Cancellation/Refund Policy</strong> page.</p>
            </div>

            <Footer/>
        </>
    )
}
export default Page;
